name: OIDC example

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    name: A simple OIDC test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1

      - name: List S3 buckets
        run: |
          aws s3 ls